### ISSUE TITLE
Weak Supervision percentage low for certain tasks

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/weak-nlp#1]
During testing of a Weak Supervision service PR I noticed that the certainty of Weak Supervision appears to be pretty low.
After a quick discussion with @jhoetter: This has to do with the used function (sigmoid) to converge to 1 (100%) -> however this results in some situations where labels appear to be unsure even though they are pretty sure:

![image](https://user-images.githubusercontent.com/91723236/172327442-c6512d7e-5b35-4e52-b0cc-e87f108806cf.png)
![image](https://user-images.githubusercontent.com/91723236/172327503-a8b5691c-598b-4195-8d47-92dce2798eb9.png)

Project Example file
[export.zip](https://github.com/code-kern-ai/weak-nlp/files/8851254/export.zip)

**Comment by jhoetter** [comment]
fixed with 0.0.9
